services:
  - type: web
    name: metricmuse-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python api.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
